Add Titan support, add missing Gemini status codes
ardek66/geminim pull request #4
Opened 2022-05-22 20:11 UTC by stellarskylark

Hello,

Here is a pull request including all my changes from the fork. Apologies for the confusion.

2022-05-22 20:39 UTC, ardek66 requested changes
Some idiomatic recommandations, I will take a more indepth look at the logic in the following days

2022-05-22 20:39 UTC, ardek66 commented on geminim.ini
> +titanpass = "titanpassword"
These new options could be written as camelCase to keep consistency with the rest of the config

2022-05-22 20:39 UTC, ardek66 commented on src/geminim.nim
> +    return response(StatusMalformedRequest, "")
The response function could be rewritten as `proc response*(code: RespStatus, meta = ""): Response` so this part here would be just `return response(StatusMalformedRequest)

2022-05-22 20:39 UTC, ardek66 commented on src/geminim.nim
> +  var token: string
These could be written as
```nim
var
    size: int
    token: string
```
since they're related and it looks nicer

2022-05-22 20:39 UTC, ardek66 commented on src/geminim.nim
> +  for i in 0 ..< params.len:
you can just do `for i in 0..params.high`

2022-05-22 20:39 UTC, ardek66 commented on src/geminim.nim
> +  if not dirExists(vhostRoot) or not ["gemini", "titan"].contains(res.scheme):
`res.scheme notin ["gemini", "titan"]`

2022-05-22 20:50 UTC, stellarskylark commented
I've made the requested style changes! Thanks

2022-05-23 15:38 UTC, ardek66 requested changes

2022-05-23 15:38 UTC, ardek66 commented on src/geminim.nim
> +  # returning this as a response is hacky but it saves me
this hack could be probably solved by moving the titan logic inside the `handle` function, which would check if the scheme is either `gemini`, in which case it would pass the request through the regular gemini code, otherwise if it's `titan` it would execute the respective titan code. This way you would have access to the socket without having to pass it to the `parseRequest` function. I think this would be a good way to allow implementation of other protocols in the future.

2022-05-23 15:38 UTC, ardek66 commented on src/geminim.nim
> +  # returning this as a response is hacky but it saves me
the `parseRequest` function could be renamed to `parseGeminiRequest` for clarity but that is not really a priority.

2022-05-23 15:39 UTC, ardek66 commented on src/geminim.nim
> +  # returning this as a response is hacky but it saves me
would probably also have to reimplement the top-level URL parsing stuff to be inside the handle function

2022-05-23 17:23 UTC, ardek66 commented on src/geminim.nim
> +  # returning this as a response is hacky but it saves me
@stellarskylark I have rewrote the `handle` so you should be able to just add your titan code to be called inside an `of "titan"` branch of the `case uri.scheme` block in `handle`

2022-05-23 19:09 UTC, stellarskylark commented
Added a commit that:

1. Copies the file parsing code into `processTitanRequest()` (this could probably be pulled out into another function at some point to avoid code reduplication)
2. Moves the CGI-processing code into a separate function so both Titan and Gemini requests can use it
3. Adds a `RESOURCE_URI` variable to the CGI environment (It's off-spec but I've seen it implemented in some servers) to ensure the full info is available to the script. (When there's a query string, neither `uri.path` nor `uri.hostname` include the extra Titan parameters)
4. Deletes the added `StatusTitan` because it's no longer needed

2022-05-23 19:25 UTC, ardek66 approved these changes

2022-05-23 19:41 UTC, ardek66 commented on src/geminim.nim
> +  let vhostRoot = server.settings.rootDir / res.hostname
A TODO here would be helpful to remind that this should not be duplicate code

2022-05-23 19:42 UTC, ardek66 approved these changes
Alright great, I'll handle the code duplication myself. Thanks for your nice contribution.

2022-05-23 19:46 UTC, merged